### ISSUE TITLE
Usage turns connection blocking

### ISSUE THREAD

**Issue by pires** [felixge/tcpkeepalive#3]
The usage of this library turns each connection into a blocking connection (fd), hence each syscall.read will block the thread it's running on. This means you will spend one thread per connection, even if you rely on goroutines for handling connections.

**Comment by felixge** [comment]
Yeah, this is mentioned first thing in the README. I ended up finding a solution to my original problem that doesn't require tcp keepalive, so I haven't had a good reason for fixing the problem. That being said, if anybody wants to send a PR, I'd merge it.

**Comment by pires** [comment]
@felixge you are right and I didn't get it at the time. Was the solution to your problem a app-layer heartbeat protocol?

**Comment by felixge** [comment]
@pires yeah, the device ended up having a feature that wasn't meant to be used for heart beats, I just didn't realize the potential to abuse it for my needs when looking through the protocol docs at first.

**Comment by gaillard** [comment]
Looks like the README is out of date now?

**Comment by felixge** [comment]
@gaillard not sure what you mean? The README mentions that the library has issues. Maybe it could be made more clear?

**Comment by gaillard** [comment]
There were a couple merges that fixed the issues no? The only issues I read in that thread are the socket being set to blocking and potential descriptor leak. Looks like that was fixed for this func https://github.com/felixge/tcpkeepalive/blob/master/keepalive.go#L69 but not for this func https://github.com/felixge/tcpkeepalive/blob/master/keepalive.go#L22 ?

**Comment by sreis** [comment]
@gaillard Wes. it wasn't fixed on that second link because we didn't know what were sensible defaults at the time and thought it best to have it be configurable.

**Comment by gaillard** [comment]
Ya it makes sense to leave the second link blocking since you have the other method non blocking. However the leaked descriptor is still there right?

**Comment by felixge** [comment]
@gaillard why does it make sense to leave a non-blocking option? I can't think of a use case.

**Comment by sreis** [comment]
The [docs](https://golang.org/pkg/os/#File.Fd) state that fd is valid until you call Close, which we do with in the defer call, and at the time we profiled our service several times and none of them indicated that there was leak there.

@gaillard Do you have a test case showing that you can share or you were just wondering if it might leak?

**Comment by gaillard** [comment]
@sreis the EnableKeepAlive() doesn't defer a Close() but SetKeepAlive() does, why the difference? Both call File().

**Comment by sreis** [comment]
I don't know but maybe @felixge can chime in.
